import { Toaster } from '@/components/ui/toaster'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className='font-sans'>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  )
}
